export const INPUT_FIELDS = [{
  label: 'Player Name',
  value: '',
  id: 'playerName',
  keyboardType: 'default',
  nextId: 'gradYear',
  returnKeyType: 'next'
}, {
  label: 'Grad Year',
  value: '',
  id: 'gradYear',
  keyboardType: 'numeric',
  nextId: 'height',
  returnKeyType: 'next'
}, {
  label: 'Height',
  value: '',
  id: 'height',
  keyboardType: 'numeric',
  nextId: 'weight',
  returnKeyType: 'next'
}, {
  label: 'Weight',
  value: '',
  id: 'weight',
  keyboardType: 'numeric',
  nextId: 'phone',
  returnKeyType: 'next'
}, {
  label: 'Phone',
  value: '',
  id: 'phone',
  keyboardType: 'phone-pad',
  nextId: 'parent',
  returnKeyType: 'next'
}, {
  label: 'Parent',
  value: '',
  id: 'parent',
  keyboardType: 'default',
  nextId: 'parentPhone',
  returnKeyType: 'next'
}, {
  label: 'Parent Phone',
  value: '',
  id: 'parentPhone',
  keyboardType: 'phone-pad',
  nextId: 'twitter',
  returnKeyType: 'next'
}, {
  label: 'Twitter',
  value: '',
  id: 'twitter',
  keyboardType: 'twitter',
  nextId: 'snapchat',
  returnKeyType: 'next'
}, {
  label: 'Snapchat',
  value: '',
  id: 'snapchat',
  keyboardType: 'default',
  nextId: 'instagram',
  returnKeyType: 'next'
}, {
  label: 'Instagram',
  value: '',
  id: 'instagram',
  keyboardType: 'default',
  nextId: 'email',
  returnKeyType: 'next'
}, {
  label: 'Email',
  value: '',
  id: 'email',
  keyboardType: 'email-address',
  nextId: 'hs',
  returnKeyType: 'next'
}, {
  label: 'High School',
  value: '',
  id: 'hs',
  keyboardType: 'default',
  nextId: 'hsCoach',
  returnKeyType: 'next'
}, {
  label: 'High School Coach',
  value: '',
  id: 'hsCoach',
  keyboardType: 'default',
  nextId: 'hsCoachPhone',
  returnKeyType: 'next'
}, {
  label: 'High School Coach Phone',
  value: '',
  id: 'hsCoachPhone',
  keyboardType: 'phone-pad',
  nextId: 'hsCoachEmail',
  returnKeyType: 'next'
}, {
  label: 'High School Coach Email',
  value: '',
  id: 'hsCoachEmail',
  keyboardType: 'email-address',
  nextId: '',
  returnKeyType: 'go'
}]
