export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const TOGGLE_FORGOT_PASSWORD = 'TOGGLE_FORGOT_PASSWORD'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const TOGGLE_CONTACT_US = 'TOGGLE_CONTACT_US'
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const RESET_REGISTER_USER_REQUEST = 'RESET_REGISTER_USER_REQUEST'

export const SET_VISIBLE_HEIGHT = 'SET_VISIBLE_HEIGHT'
export const SET_VISIBLE_WIDTH = 'SET_VISIBLE_WIDTH'

export const SET_SPINNER = 'SET_SPINNER'

export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'
export const SET_PLAYER_IMAGE = 'SET_PLAYER_IMAGE'

export const SET_TEAM_DATA = 'SET_TEAM_DATA'
export const SET_TEAM_COACH_IMAGE = 'SET_TEAM_COACH_IMAGE'

export const SET_REGISTER_DATA = 'SET_REGISTER_DATA'
