export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const TOGGLE_FORGOT_PASSWORD = 'TOGGLE_FORGOT_PASSWORD'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const TOGGLE_CONTACT_US = 'TOGGLE_CONTACT_US'
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const RESET_REGISTER_USER_REQUEST = 'RESET_REGISTER_USER_REQUEST'

export const SET_VISIBLE_HEIGHT = 'SET_VISIBLE_HEIGHT'
export const SET_VISIBLE_WIDTH = 'SET_VISIBLE_WIDTH'

export const SET_SPINNER = 'SET_SPINNER'

export const SET_TEAM_COACH_IMAGE = 'SET_TEAM_COACH_IMAGE'

export const SET_REGISTER_DATA = 'SET_REGISTER_DATA'

export const COACH_FETCH_REQUEST = 'COACH_FETCH_REQUEST'
export const COACH_FETCH_SUCCESS = 'COACH_FETCH_SUCCESS'
export const COACH_FETCH_FAILURE = 'COACH_FETCH_FAILURE'

export const COACH_ADD_REQUEST = 'COACH_ADD_REQUEST'
export const COACH_ADD_SUCCESS = 'COACH_ADD_SUCCESS'
export const COACH_ADD_FAILURE = 'COACH_ADD_FAILURE'

export const COACH_DELETE_REQUEST = 'COACH_DELETE_REQUEST'
export const COACH_DELETE_SUCCESS = 'COACH_DELETE_SUCCESS'
export const COACH_DELETE_FAILURE = 'COACH_DELETE_FAILURE'

export const SET_COACH_DATA = 'SET_COACH_DATA'
export const SET_COACH_IMAGE = 'SET_COACH_IMAGE'
export const RESET_COACH_DATA = 'RESET_COACH_DATA'

export const STAFF_FETCH_REQUEST = 'STAFF_FETCH_REQUEST'
export const STAFF_FETCH_SUCCESS = 'STAFF_FETCH_SUCCESS'
export const STAFF_FETCH_FAILURE = 'STAFF_FETCH_FAILURE'

export const STAFF_ADD_REQUEST = 'STAFF_ADD_REQUEST'
export const STAFF_ADD_SUCCESS = 'STAFF_ADD_SUCCESS'
export const STAFF_ADD_FAILURE = 'STAFF_ADD_FAILURE'

export const STAFF_DELETE_REQUEST = 'STAFF_DELETE_REQUEST'
export const STAFF_DELETE_SUCCESS = 'STAFF_DELETE_SUCCESS'
export const STAFF_DELETE_FAILURE = 'STAFF_DELETE_FAILURE'

export const SET_STAFF_DATA = 'SET_STAFF_DATA'
export const SET_STAFF_IMAGE = 'SET_STAFF_IMAGE'
export const RESET_STAFF_DATA = 'RESET_STAFF_DATA'

export const TEAM_FETCH_REQUEST = 'TEAM_FETCH_REQUEST'
export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS'
export const TEAM_FETCH_FAILURE = 'TEAM_FETCH_FAILURE'

export const TEAM_ADD_REQUEST = 'TEAM_ADD_REQUEST'
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS'
export const TEAM_ADD_FAILURE = 'TEAM_ADD_FAILURE'

export const TEAM_DELETE_REQUEST = 'TEAM_DELETE_REQUEST'
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS'
export const TEAM_DELETE_FAILURE = 'TEAM_DELETE_FAILURE'

export const SET_TEAM_DATA = 'SET_TEAM_DATA'
export const SET_TEAM_IMAGE = 'SET_TEAM_IMAGE'
export const RESET_TEAM_DATA = 'RESET_TEAM_DATA'

export const PLAYER_FETCH_REQUEST = 'PLAYER_FETCH_REQUEST'
export const PLAYER_FETCH_SUCCESS = 'PLAYER_FETCH_SUCCESS'
export const PLAYER_FETCH_FAILURE = 'PLAYER_FETCH_FAILURE'

export const PLAYER_ADD_REQUEST = 'PLAYER_ADD_REQUEST'
export const PLAYER_ADD_SUCCESS = 'PLAYER_ADD_SUCCESS'
export const PLAYER_ADD_FAILURE = 'PLAYER_ADD_FAILURE'

export const PLAYER_DELETE_REQUEST = 'PLAYER_DELETE_REQUEST'
export const PLAYER_DELETE_SUCCESS = 'PLAYER_DELETE_SUCCESS'
export const PLAYER_DELETE_FAILURE = 'PLAYER_DELETE_FAILURE'

export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'
export const SET_PLAYER_IMAGE = 'SET_PLAYER_IMAGE'
export const RESET_PLAYER_DATA = 'RESET_PLAYER_DATA'

export const HS_FETCH_REQUEST = 'HS_FETCH_REQUEST'
export const HS_FETCH_SUCCESS = 'HS_FETCH_SUCCESS'
export const HS_FETCH_FAILURE = 'HS_FETCH_FAILURE'

export const HS_ADD_REQUEST = 'HS_ADD_REQUEST'
export const HS_ADD_SUCCESS = 'HS_ADD_SUCCESS'
export const HS_ADD_FAILURE = 'HS_ADD_FAILURE'

export const HS_DELETE_REQUEST = 'HS_DELETE_REQUEST'
export const HS_DELETE_SUCCESS = 'HS_DELETE_SUCCESS'
export const HS_DELETE_FAILURE = 'HS_DELETE_FAILURE'

export const SET_HS_DATA = 'SET_HS_DATA'
export const RESET_HS_DATA = 'RESET_HS_DATA'
