export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const STATES_FETCH_REQUEST = 'STATES_FETCH_REQUEST'
export const TOGGLE_FORGOT_PASSWORD = 'TOGGLE_FORGOT_PASSWORD'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const TOGGLE_CONTACT_US = 'TOGGLE_CONTACT_US'
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL'
export const TOGGLE_TEAM_NAME_MODAL = 'TOGGLE_TEAM_NAME_MODAL'
export const TOGGLE_AGE_GROUP_MODAL = 'TOGGLE_AGE_GROUP_MODAL'
export const TOGGLE_EVENT_MODAL = 'TOGGLE_EVENT_MODAL'
export const TOGGLE_PLAYER_MODAL = 'TOGGLE_PLAYER_MODAL'
export const TOGGLE_STATE_MODAL = 'TOGGLE_STATE_MODAL'

export const SET_TEAM_FILTER = 'SET_TEAM_FILTER'
export const SET_AGE_GROUP_FILTER = 'SET_AGE_GROUP_FILTER'
export const SET_STATE_FILTER = 'SET_STATE_FILTER'
export const SET_REGION_FILTER = 'SET_REGION_FILTER'
export const SET_EVENT_FILTER = 'SET_EVENT_FILTER'
export const SET_PLAYER_FIRST_FILTER = 'SET_PLAYER_FIRST_FILTER'
export const SET_PLAYER_LAST_FILTER = 'SET_PLAYER_LAST_FILTER'

export const SET_PLAYER = 'SET_PLAYER'
export const SET_TEAM = 'SET_TEAM'
export const SET_TEAM_ROUTE = 'SET_TEAM_ROUTE'

export const SET_FILTERED_DATA_REQUEST = 'SET_FILTERED_DATA_REQUEST'
export const SET_FILTERED_DATA_SUCCESS = 'SET_FILTERED_DATA_SUCCESS'
export const SET_FILTERED_DATA_FAILURE = 'SET_FILTERED_DATA'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const SET_REGISTER_IS_RECRUITER = 'SET_REGISTER_IS_RECRUITER'
export const SET_REGISTER_IS_PLAYER = 'SET_REGISTER_IS_PLAYER'
export const SET_REGISTER_IS_PARENT = 'SET_REGISTER_IS_PARENT'
export const SET_REGISTER_IS_COORDINATOR = 'SET_REGISTER_IS_COORDINATOR'
export const SET_REGISTER_IS_COACH = 'SET_REGISTER_IS_COACH'
export const RESET_REGISTER_USER_REQUEST = 'RESET_REGISTER_USER_REQUEST'

export const ROLES_FETCH_REQUEST = 'ROLES_FETCH_REQUEST'
export const ROLES_FETCH_SUCCESS = 'ROLES_FETCH_SUCCESS'
export const ROLES_FETCH_FAILURE = 'ROLES_FETCH_FAILURE'

export const ROLES_ADD_REQUEST = 'ROLES_ADD_REQUEST'
export const ROLES_ADD_SUCCESS = 'ROLES_ADD_SUCCESS'
export const ROLES_ADD_FAILURE = 'ROLES_ADD_FAILURE'

export const SET_VISIBLE_HEIGHT = 'SET_VISIBLE_HEIGHT'
export const SET_VISIBLE_WIDTH = 'SET_VISIBLE_WIDTH'

export const SET_SPINNER = 'SET_SPINNER'

export const SET_TEAM_COACH_IMAGE = 'SET_TEAM_COACH_IMAGE'

export const SET_REGISTER_DATA = 'SET_REGISTER_DATA'

export const COACH_BY_ID_FETCH_REQUEST = 'COACH_BY_ID_FETCH_REQUEST'
export const COACH_BY_ID_FETCH_SUCCESS = 'COACH_BY_ID_FETCH_SUCCESS'
export const COACH_BY_ID_FETCH_FAILURE = 'COACH_BY_ID_FETCH_FAILURE'

export const COACH_FETCH_REQUEST = 'COACH_FETCH_REQUEST'
export const COACH_FETCH_SUCCESS = 'COACH_FETCH_SUCCESS'
export const COACH_FETCH_FAILURE = 'COACH_FETCH_FAILURE'

export const COACH_ADD_REQUEST = 'COACH_ADD_REQUEST'
export const COACH_ADD_SUCCESS = 'COACH_ADD_SUCCESS'
export const COACH_ADD_FAILURE = 'COACH_ADD_FAILURE'

export const COACH_DELETE_REQUEST = 'COACH_DELETE_REQUEST'
export const COACH_DELETE_SUCCESS = 'COACH_DELETE_SUCCESS'
export const COACH_DELETE_FAILURE = 'COACH_DELETE_FAILURE'

export const SET_COACH_ID = 'SET_COACH_ID'
export const SET_COACH_DATA = 'SET_COACH_DATA'
export const SET_COACH_IMAGE = 'SET_COACH_IMAGE'
export const RESET_COACH_DATA = 'RESET_COACH_DATA'

export const STAFF_BY_ID_FETCH_REQUEST = 'STAFF_BY_ID_FETCH_REQUEST'
export const STAFF_BY_ID_FETCH_SUCCESS = 'STAFF_BY_ID_FETCH_SUCCESS'
export const STAFF_BY_ID_FETCH_FAILURE = 'STAFF_BY_ID_FETCH_FAILURE'

export const STAFF_FETCH_REQUEST = 'STAFF_FETCH_REQUEST'
export const STAFF_FETCH_SUCCESS = 'STAFF_FETCH_SUCCESS'
export const STAFF_FETCH_FAILURE = 'STAFF_FETCH_FAILURE'

export const STAFF_ADD_REQUEST = 'STAFF_ADD_REQUEST'
export const STAFF_ADD_SUCCESS = 'STAFF_ADD_SUCCESS'
export const STAFF_ADD_FAILURE = 'STAFF_ADD_FAILURE'

export const STAFF_DELETE_REQUEST = 'STAFF_DELETE_REQUEST'
export const STAFF_DELETE_SUCCESS = 'STAFF_DELETE_SUCCESS'
export const STAFF_DELETE_FAILURE = 'STAFF_DELETE_FAILURE'

export const SET_STAFF_ID = 'SET_STAFF_ID'
export const SET_STAFF_DATA = 'SET_STAFF_DATA'
export const SET_STAFF_IMAGE = 'SET_STAFF_IMAGE'
export const RESET_STAFF_DATA = 'RESET_STAFF_DATA'

export const TEAM_BY_ID_FETCH_REQUEST = 'TEAM_BY_ID_FETCH_REQUEST'
export const TEAM_BY_ID_FETCH_SUCCESS = 'TEAM_BY_ID_FETCH_SUCCESS'
export const TEAM_BY_ID_FETCH_FAILURE = 'TEAM_BY_ID_FETCH_FAILURE'

export const TEAM_FETCH_REQUEST = 'TEAM_FETCH_REQUEST'
export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS'
export const TEAM_FETCH_FAILURE = 'TEAM_FETCH_FAILURE'

export const TEAM_ADD_REQUEST = 'TEAM_ADD_REQUEST'
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS'
export const TEAM_ADD_FAILURE = 'TEAM_ADD_FAILURE'

export const TEAM_DELETE_REQUEST = 'TEAM_DELETE_REQUEST'
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS'
export const TEAM_DELETE_FAILURE = 'TEAM_DELETE_FAILURE'

export const SET_TEAM_ID = 'SET_TEAM_ID'
export const SET_TEAM_DATA = 'SET_TEAM_DATA'
export const SET_TEAM_STATE = 'SET_TEAM_STATE'
export const SET_TEAM_REGION = 'SET_TEAM_REGION'
export const SET_TEAM_IMAGE = 'SET_TEAM_IMAGE'
export const RESET_TEAM_DATA = 'RESET_TEAM_DATA'

export const PLAYER_BY_ID_FETCH_REQUEST = 'PLAYER_BY_ID_FETCH_REQUEST'
export const PLAYER_BY_ID_FETCH_SUCCESS = 'PLAYER_BY_ID_FETCH_SUCCESS'
export const PLAYER_BY_ID_FETCH_FAILURE = 'PLAYER_BY_ID_FETCH_FAILURE'

export const PLAYER_FETCH_REQUEST = 'PLAYER_FETCH_REQUEST'
export const PLAYER_FETCH_SUCCESS = 'PLAYER_FETCH_SUCCESS'
export const PLAYER_FETCH_FAILURE = 'PLAYER_FETCH_FAILURE'

export const PLAYER_ADD_REQUEST = 'PLAYER_ADD_REQUEST'
export const PLAYER_ADD_SUCCESS = 'PLAYER_ADD_SUCCESS'
export const PLAYER_ADD_FAILURE = 'PLAYER_ADD_FAILURE'

export const PLAYER_DELETE_REQUEST = 'PLAYER_DELETE_REQUEST'
export const PLAYER_DELETE_SUCCESS = 'PLAYER_DELETE_SUCCESS'
export const PLAYER_DELETE_FAILURE = 'PLAYER_DELETE_FAILURE'

export const SET_PLAYER_ID = 'SET_PLAYER_ID'
export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'
export const SET_PLAYER_IMAGE = 'SET_PLAYER_IMAGE'
export const RESET_PLAYER_DATA = 'RESET_PLAYER_DATA'
export const SET_PLAYER_AGE_GROUP = 'SET_PLAYER_AGE_GROUP'

export const HS_BY_ID_FETCH_REQUEST = 'HS_BY_ID_FETCH_REQUEST'
export const HS_BY_ID_FETCH_SUCCESS = 'HS_BY_ID_FETCH_SUCCESS'
export const HS_BY_ID_FETCH_FAILURE = 'HS_BY_ID_FETCH_FAILURE'

export const HS_FETCH_REQUEST = 'HS_FETCH_REQUEST'
export const HS_FETCH_SUCCESS = 'HS_FETCH_SUCCESS'
export const HS_FETCH_FAILURE = 'HS_FETCH_FAILURE'

export const HS_ADD_REQUEST = 'HS_ADD_REQUEST'
export const HS_ADD_SUCCESS = 'HS_ADD_SUCCESS'
export const HS_ADD_FAILURE = 'HS_ADD_FAILURE'

export const HS_DELETE_REQUEST = 'HS_DELETE_REQUEST'
export const HS_DELETE_SUCCESS = 'HS_DELETE_SUCCESS'
export const HS_DELETE_FAILURE = 'HS_DELETE_FAILURE'

export const SET_HS_ID = 'SET_HS_ID'
export const SET_HS_DATA = 'SET_HS_DATA'
export const RESET_HS_DATA = 'RESET_HS_DATA'

export const ROSTER_BY_ID_FETCH_REQUEST = 'ROSTER_BY_ID_FETCH_REQUEST'
export const ROSTER_BY_ID_FETCH_SUCCESS = 'ROSTER_BY_ID_FETCH_SUCCESS'
export const ROSTER_BY_ID_FETCH_FAILURE = 'ROSTER_BY_ID_FETCH_FAILURE'

export const ROSTER_FETCH_REQUEST = 'ROSTER_FETCH_REQUEST'
export const ROSTER_FETCH_SUCCESS = 'ROSTER_FETCH_SUCCESS'
export const ROSTER_FETCH_FAILURE = 'ROSTER_FETCH_FAILURE'

export const ROSTER_ADD_REQUEST = 'ROSTER_ADD_REQUEST'
export const ROSTER_ADD_SUCCESS = 'ROSTER_ADD_SUCCESS'
export const ROSTER_ADD_FAILURE = 'ROSTER_ADD_FAILURE'

export const ROSTER_DELETE_REQUEST = 'ROSTER_DELETE_REQUEST'
export const ROSTER_DELETE_SUCCESS = 'ROSTER_DELETE_SUCCESS'
export const ROSTER_DELETE_FAILURE = 'ROSTER_DELETE_FAILURE'

export const SET_ROSTER_ID = 'SET_ROSTER_ID'
export const SET_ROSTER_PLAYER = 'SET_ROSTER_PLAYER'
export const SET_ROSTER_STAFF = 'SET_ROSTER_STAFF'
export const RESET_ROSTER_DATA = 'RESET_ROSTER_DATA'

export const TEAMS_BY_ID_FETCH_REQUEST = 'TEAMS_BY_ID_FETCH_REQUEST'
export const TEAMS_BY_ID_FETCH_SUCCESS = 'TEAMS_BY_ID_FETCH_SUCCESS'
export const TEAMS_BY_ID_FETCH_FAILURE = 'TEAMS_BY_ID_FETCH_FAILURE'

export const TEAMS_BY_COACH_ID_FETCH_REQUEST = 'TEAMS_BY_COACH_ID_FETCH_REQUEST'
export const TEAMS_BY_COACH_ID_FETCH_SUCCESS = 'TEAMS_BY_COACH_ID_FETCH_SUCCESS'
export const TEAMS_BY_COACH_ID_FETCH_FAILURE = 'TEAMS_BY_COACH_ID_FETCH_FAILURE'

export const TEAMS_FETCH_REQUEST = 'TEAMS_FETCH_REQUEST'
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS'
export const TEAMS_FETCH_FAILURE = 'TEAMS_FETCH_FAILURE'

export const TEAMS_ADD_REQUEST = 'TEAMS_ADD_REQUEST'
export const TEAMS_ADD_SUCCESS = 'TEAMS_ADD_SUCCESS'
export const TEAMS_ADD_FAILURE = 'TEAMS_ADD_FAILURE'

export const TEAMS_DELETE_REQUEST = 'TEAMS_DELETE_REQUEST'
export const TEAMS_DELETE_SUCCESS = 'TEAMS_DELETE_SUCCESS'
export const TEAMS_DELETE_FAILURE = 'TEAMS_DELETE_FAILURE'
